// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"shop/ent/cart"
	"shop/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CartUpdate is the builder for updating Cart entities.
type CartUpdate struct {
	config
	hooks    []Hook
	mutation *CartMutation
}

// Where appends a list predicates to the CartUpdate builder.
func (_u *CartUpdate) Where(ps ...predicate.Cart) *CartUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *CartUpdate) SetProductID(v int) *CartUpdate {
	_u.mutation.ResetProductID()
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *CartUpdate) SetNillableProductID(v *int) *CartUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// AddProductID adds value to the "product_id" field.
func (_u *CartUpdate) AddProductID(v int) *CartUpdate {
	_u.mutation.AddProductID(v)
	return _u
}

// SetCount sets the "count" field.
func (_u *CartUpdate) SetCount(v int) *CartUpdate {
	_u.mutation.ResetCount()
	_u.mutation.SetCount(v)
	return _u
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_u *CartUpdate) SetNillableCount(v *int) *CartUpdate {
	if v != nil {
		_u.SetCount(*v)
	}
	return _u
}

// AddCount adds value to the "count" field.
func (_u *CartUpdate) AddCount(v int) *CartUpdate {
	_u.mutation.AddCount(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CartUpdate) SetUserID(v int) *CartUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CartUpdate) SetNillableUserID(v *int) *CartUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CartUpdate) AddUserID(v int) *CartUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CartUpdate) SetCreatedAt(v time.Time) *CartUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CartUpdate) SetNillableCreatedAt(v *time.Time) *CartUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the CartMutation object of the builder.
func (_u *CartUpdate) Mutation() *CartMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CartUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CartUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CartUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CartUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CartUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(cart.Table, cart.Columns, sqlgraph.NewFieldSpec(cart.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(cart.FieldProductID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProductID(); ok {
		_spec.AddField(cart.FieldProductID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Count(); ok {
		_spec.SetField(cart.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.AddField(cart.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(cart.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(cart.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(cart.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cart.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CartUpdateOne is the builder for updating a single Cart entity.
type CartUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CartMutation
}

// SetProductID sets the "product_id" field.
func (_u *CartUpdateOne) SetProductID(v int) *CartUpdateOne {
	_u.mutation.ResetProductID()
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *CartUpdateOne) SetNillableProductID(v *int) *CartUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// AddProductID adds value to the "product_id" field.
func (_u *CartUpdateOne) AddProductID(v int) *CartUpdateOne {
	_u.mutation.AddProductID(v)
	return _u
}

// SetCount sets the "count" field.
func (_u *CartUpdateOne) SetCount(v int) *CartUpdateOne {
	_u.mutation.ResetCount()
	_u.mutation.SetCount(v)
	return _u
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_u *CartUpdateOne) SetNillableCount(v *int) *CartUpdateOne {
	if v != nil {
		_u.SetCount(*v)
	}
	return _u
}

// AddCount adds value to the "count" field.
func (_u *CartUpdateOne) AddCount(v int) *CartUpdateOne {
	_u.mutation.AddCount(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CartUpdateOne) SetUserID(v int) *CartUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CartUpdateOne) SetNillableUserID(v *int) *CartUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CartUpdateOne) AddUserID(v int) *CartUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CartUpdateOne) SetCreatedAt(v time.Time) *CartUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CartUpdateOne) SetNillableCreatedAt(v *time.Time) *CartUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the CartMutation object of the builder.
func (_u *CartUpdateOne) Mutation() *CartMutation {
	return _u.mutation
}

// Where appends a list predicates to the CartUpdate builder.
func (_u *CartUpdateOne) Where(ps ...predicate.Cart) *CartUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CartUpdateOne) Select(field string, fields ...string) *CartUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Cart entity.
func (_u *CartUpdateOne) Save(ctx context.Context) (*Cart, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CartUpdateOne) SaveX(ctx context.Context) *Cart {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CartUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CartUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CartUpdateOne) sqlSave(ctx context.Context) (_node *Cart, err error) {
	_spec := sqlgraph.NewUpdateSpec(cart.Table, cart.Columns, sqlgraph.NewFieldSpec(cart.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Cart.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cart.FieldID)
		for _, f := range fields {
			if !cart.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cart.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(cart.FieldProductID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProductID(); ok {
		_spec.AddField(cart.FieldProductID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Count(); ok {
		_spec.SetField(cart.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.AddField(cart.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(cart.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(cart.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(cart.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Cart{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cart.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
