// Code generated by ent, DO NOT EDIT.

package ent

import (
	"shop/ent/cart"
	"shop/ent/schema"
	"shop/ent/user"
	"shop/ent/walet"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cartFields := schema.Cart{}.Fields()
	_ = cartFields
	// cartDescCreatedAt is the schema descriptor for created_at field.
	cartDescCreatedAt := cartFields[3].Descriptor()
	// cart.DefaultCreatedAt holds the default value on creation for the created_at field.
	cart.DefaultCreatedAt = cartDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	waletFields := schema.Walet{}.Fields()
	_ = waletFields
	// waletDescCreatedAt is the schema descriptor for created_at field.
	waletDescCreatedAt := waletFields[2].Descriptor()
	// walet.DefaultCreatedAt holds the default value on creation for the created_at field.
	walet.DefaultCreatedAt = waletDescCreatedAt.Default.(func() time.Time)
}
