// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cart is the predicate function for cart builders.
type Cart func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Walet is the predicate function for walet builders.
type Walet func(*sql.Selector)
